Add Eslint, Prettier, Husky
ACM-VIT/dolos pull request #33
Opened 2020-10-05 05:15 UTC by vj-abishek

This PR solves #19 this problem.

2020-10-05 15:45 UTC, YashKumarVerma requested changes

2020-10-05 15:45 UTC, YashKumarVerma commented on package.json
> +    "prettier": "prettier \"**/*.{js,jsx,css,json}\"",
we won't be having any .css files as this is an api

2020-10-05 15:45 UTC, YashKumarVerma commented on package.json
> +    "**/*.{js,jsx,css}": [
css, jsx not required.

2020-10-06 02:36 UTC, vj-abishek commented on package.json
> +    "**/*.{js,jsx,css}": [
Okay, I will fix it.

2020-10-06 16:12 UTC, vj-abishek commented
@YashKumarVerma There is an issue with package-lock.json. So It is getting difficult to resolve the conflict. 

![Annotation 2020-10-06 213442](https://user-images.githubusercontent.com/43115551/95227596-eb509c80-081b-11eb-98e9-f8ee5273926b.jpg)

I tried in my local machine and  `gitpod.io`. In both platforms, it is not working.
I cannot even install the package. Only getting this issue from recent PR

2020-10-07 16:06 UTC, YashKumarVerma commented
Requesting to resolve merge conflicts.

2020-10-08 02:10 UTC, vj-abishek commented
Working on it

2020-10-08 04:54 UTC, vj-abishek commented
@YashKumarVerma There is an error in the database connection. So disabling `eslint` and `test` in pre-commit hook.

2020-10-08 16:33 UTC, YashKumarVerma approved these changes

2020-10-10 04:09 UTC, merged

2020-10-10 04:10 UTC, lopeselio commented
Changes have been merged