Added env variables for db connectivity
ACM-VIT/dolos pull request #44
Opened 2020-10-06 17:57 UTC by shadabshaikh0

Raised PR for this issue
[https://github.com/ACM-VIT/dolos/issues/40](url)

2020-10-06 20:16 UTC, YashKumarVerma requested changes

2020-10-06 20:16 UTC, YashKumarVerma commented on src/database.js
> +  password: process.env.DB_PASSWORD
use or operator to set the default values.

2020-10-07 06:06 UTC, shadabshaikh0 commented
Added default values, please review it.

2020-10-07 16:08 UTC, YashKumarVerma approved these changes

2020-10-07 16:10 UTC, YashKumarVerma commented
Would recommend adding these entries to `.env.example` as well

2020-10-07 16:35 UTC, shadabshaikh0 commented
Added .env.example

2020-10-08 16:36 UTC, YashKumarVerma approved these changes

2020-10-12 08:31 UTC, lopeselio commented
There are some conflicts which need to be resolved @shadabshaikh0

2020-10-13 11:05 UTC, merged